personality = "pragmatic"
model_provider = "openrouter"
model = "openai/gpt-5"
model_reasoning_effort = "high"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "CODEX_API_KEY"
